script:
- rsync -r --delete-after -e "ssh -o StrictHostKeyChecking=no" --quiet $TRAVIS_BUILD_DIR
  $USER:$RSYNC_PASSWORD@$HOST:/home/avestaadmin/landing-page-avesta
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_65eeaec794da_key -iv $encrypted_65eeaec794da_iv
  -in secret -out private.key -d
