script:
- docker build -t ansible-alpine deploy
- docker run --rm -it -v $(pwd)/deploy:/ansible/playbooks ansible-alpine ansible-playbook -i /ansible/playbooks/inventory /ansible/playbooks/avesta-center.yaml
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_65eeaec794da_key -iv $encrypted_65eeaec794da_iv
  -in secret -out deploy/private.key -d
